<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>

<p>
<div class="field regulation required">
    <label for="company_name" class="label"><span><?php /* @escapeNotVerified */
            echo __('Company name') ?></span></label>
    <div class="control">
        <input type="text" checked name="company_name" id="company_name" title="<?php /* @escapeNotVerified */
        echo __('Regulation') ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<div class="field regulation required">
    <label for="vat_number" class="label"><span><?php /* @escapeNotVerified */
            echo __('VAT number') ?></span></label>
    <div class="control">
        <input type="text" checked name="vat_number" id="vat_number" title="<?php /* @escapeNotVerified */
        echo __('Regulation') ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
</p></fieldset>