<?php exit("Asdf"); ?>
<div class="field field-name-firstname required">
    <label class="label" for="company_name">
        <span><?php __("Company name") ?></span>
    </label>

    <div class="control">
        <input type="text" id="company_name" name="company_name" value="" title="Company name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
    </div>
</div>
<div class="field field-name-firstname required">
    <label class="label" for="vat_number">
        <span><?php __("VAT number") ?></span>
    </label>

    <div class="control">
        <input type="text" id="vat_number" name="vat_number" value="" title="VAT Number" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
    </div>
</div>